#!/bin/bash
# Add the current directory to the path
# Get full path to the script no matter where it is called from
# https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo "PATH=$PATH:$SCRIPTPATH"